/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ailatrieuphu;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.net.Socket;
import java.time.LocalDateTime;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Admin
 */
public class GamePlay extends javax.swing.JFrame {

    /**
     * Creates new form GamePlay
     */
    ImageIcon btnxanhduong;
    ImageIcon btndo;
    ImageIcon btnvang;
    ImageIcon btnxanhla;

    int dapan;
    int cauhoi = 1;
    int dapannguoichoi;
    boolean flag = true;

    Socket socket;
    DataInputStream dis;
    DataOutputStream dos;

    public boolean kiemtradapan() {
        return dapannguoichoi == dapan;
    }

    public void Load() {
        btnxanhduong = new ImageIcon("img/xanhduong.png");
        btndo = new ImageIcon("img/do.png");
        btnxanhla = new ImageIcon("img/xanhlacay.png");
        btnvang = new ImageIcon("img/vang.png");

        try {
            socket = new Socket("127.0.0.1", 3000);
            dis = new DataInputStream(socket.getInputStream());
            dos = new DataOutputStream(socket.getOutputStream());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "Khong ket loi dc mang");
        }

    }

    public String cat(String s) {
        String a = "<html>";
        char[] b = ("Cau" + String.valueOf(cauhoi) + " : " + s).toCharArray();
        int count = 0;
        boolean flag = false;
        for (int i = 0; i < b.length; i++) {
            count++;
            a = a + b[i];
            if (count % 40 == 0) {
                flag = true;
            }
            if ((flag) && (Character.toString(b[i]).equals("\b"))) {
                a = a + "<br>";
                flag = false;
            }
        }
        return a;
    }

    public GamePlay() {
        initComponents();
        setSize(800, 600);
        setResizable(false);
        Load();
        loadCauhoi(cauhoi);
        setTitle("Ai là triệu phú");
    }

    public void loadCauhoi(int i) {
        resetButton();
        try {
            dos.writeUTF(String.valueOf(i));
            String s = dis.readUTF();
            resetButton();
            set_Text(s);
            lbSocauhoi.setText(String.valueOf(i));
        } catch (IOException ex) {
            Logger.getLogger(GamePlay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void resetButton() {

        setRolloverAllbutton(true);
        btnA.setIcon(btnxanhduong);
        btnB.setIcon(btnxanhduong);
        btnC.setIcon(btnxanhduong);
        btnD.setIcon(btnxanhduong);

        flag = true;
    }

    public void set_Text(String s) {
        String[] a;
        a = s.split("\\$");
        lbcauhoi.setText(cat(a[0]));
        lbA.setText("A:" + a[1]);
        lbB.setText("B:" + a[2]);
        lbC.setText("C:" + a[3]);
        lbD.setText("D:" + a[4]);
        this.dapan = Integer.parseInt(a[5]);
    }

    public void setRolloverAllbutton(boolean a) {
        btnA.setRolloverEnabled(a);
        btnB.setRolloverEnabled(a);
        btnC.setRolloverEnabled(a);
        btnD.setRolloverEnabled(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbB = new javax.swing.JLabel();
        lbC = new javax.swing.JLabel();
        lbD = new javax.swing.JLabel();
        lbA = new javax.swing.JLabel();
        btnA = new javax.swing.JButton();
        btnB = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnD = new javax.swing.JButton();
        btnTieptuc = new javax.swing.JButton();
        btnDungchoi = new javax.swing.JButton();
        lbSocauhoi = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbcauhoi = new javax.swing.JLabel();
        lbBGcauhoi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbB.setForeground(new java.awt.Color(0, 255, 255));
        lbB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbB);
        lbB.setBounds(330, 390, 300, 50);

        lbC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbC.setForeground(new java.awt.Color(0, 255, 255));
        lbC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbC);
        lbC.setBounds(10, 490, 300, 50);

        lbD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbD.setForeground(new java.awt.Color(0, 255, 255));
        lbD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbD);
        lbD.setBounds(330, 490, 300, 50);

        lbA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbA.setForeground(new java.awt.Color(0, 255, 255));
        lbA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbA);
        lbA.setBounds(10, 390, 300, 50);

        btnA.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnA.setForeground(new java.awt.Color(255, 0, 0));
        btnA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ailatrieuphu/xanhduong.png"))); // NOI18N
        btnA.setContentAreaFilled(false);
        btnA.setMaximumSize(new java.awt.Dimension(300, 50));
        btnA.setMinimumSize(new java.awt.Dimension(300, 50));
        btnA.setPreferredSize(new java.awt.Dimension(300, 50));
        btnA.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Ailatrieuphu/vang.png"))); // NOI18N
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });
        getContentPane().add(btnA);
        btnA.setBounds(10, 390, 300, 50);

        btnB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnB.setForeground(new java.awt.Color(255, 0, 0));
        btnB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ailatrieuphu/xanhduong.png"))); // NOI18N
        btnB.setContentAreaFilled(false);
        btnB.setMaximumSize(new java.awt.Dimension(300, 50));
        btnB.setMinimumSize(new java.awt.Dimension(300, 50));
        btnB.setPreferredSize(new java.awt.Dimension(300, 50));
        btnB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Ailatrieuphu/vang.png"))); // NOI18N
        btnB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBMousePressed(evt);
            }
        });
        btnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBActionPerformed(evt);
            }
        });
        getContentPane().add(btnB);
        btnB.setBounds(330, 390, 300, 50);

        btnC.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnC.setForeground(new java.awt.Color(255, 0, 0));
        btnC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ailatrieuphu/xanhduong.png"))); // NOI18N
        btnC.setContentAreaFilled(false);
        btnC.setMaximumSize(new java.awt.Dimension(300, 50));
        btnC.setMinimumSize(new java.awt.Dimension(300, 50));
        btnC.setPreferredSize(new java.awt.Dimension(300, 50));
        btnC.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Ailatrieuphu/vang.png"))); // NOI18N
        btnC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCMousePressed(evt);
            }
        });
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        getContentPane().add(btnC);
        btnC.setBounds(10, 490, 300, 50);

        btnD.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnD.setForeground(new java.awt.Color(255, 0, 0));
        btnD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ailatrieuphu/xanhduong.png"))); // NOI18N
        btnD.setContentAreaFilled(false);
        btnD.setMaximumSize(new java.awt.Dimension(300, 50));
        btnD.setMinimumSize(new java.awt.Dimension(300, 50));
        btnD.setPreferredSize(new java.awt.Dimension(300, 50));
        btnD.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Ailatrieuphu/vang.png"))); // NOI18N
        btnD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDMousePressed(evt);
            }
        });
        btnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDActionPerformed(evt);
            }
        });
        getContentPane().add(btnD);
        btnD.setBounds(330, 490, 300, 50);

        btnTieptuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ailatrieuphu/img/btnTieptucxanhduong.png"))); // NOI18N
        btnTieptuc.setContentAreaFilled(false);
        btnTieptuc.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Ailatrieuphu/img/btnTieptucxanh.png"))); // NOI18N
        btnTieptuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTieptucActionPerformed(evt);
            }
        });
        getContentPane().add(btnTieptuc);
        btnTieptuc.setBounds(560, 300, 200, 50);

        btnDungchoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ailatrieuphu/img/btnDungchoixanhduong.png"))); // NOI18N
        btnDungchoi.setContentAreaFilled(false);
        btnDungchoi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Ailatrieuphu/img/btnDungchoixanh.png"))); // NOI18N
        btnDungchoi.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Ailatrieuphu/img/btnDungchoixanh.png"))); // NOI18N
        btnDungchoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDungchoiActionPerformed(evt);
            }
        });
        getContentPane().add(btnDungchoi);
        btnDungchoi.setBounds(520, 60, 260, 50);

        lbSocauhoi.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbSocauhoi.setForeground(new java.awt.Color(255, 204, 102));
        lbSocauhoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSocauhoi.setText("1");
        lbSocauhoi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbSocauhoi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbSocauhoi);
        lbSocauhoi.setBounds(630, 200, 50, 50);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ailatrieuphu/img/button1.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Ailatrieuphu/img/button2.png"))); // NOI18N
        getContentPane().add(jButton1);
        jButton1.setBounds(630, 200, 50, 50);

        lbcauhoi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbcauhoi.setForeground(new java.awt.Color(255, 51, 0));
        lbcauhoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbcauhoi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbcauhoi);
        lbcauhoi.setBounds(70, 60, 420, 290);

        lbBGcauhoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ailatrieuphu/cauhoi.png"))); // NOI18N
        getContentPane().add(lbBGcauhoi);
        lbBGcauhoi.setBounds(50, 50, 454, 310);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ailatrieuphu/Gamebg.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBMousePressed

    }//GEN-LAST:event_btnBMousePressed

    private void btnCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCMousePressed

    }//GEN-LAST:event_btnCMousePressed

    private void btnDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDMousePressed

    }//GEN-LAST:event_btnDMousePressed

    private void btnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBActionPerformed
        if (flag) {
            dapannguoichoi = 2;
            flag = false;
            setRolloverAllbutton(false);
            if (kiemtradapan()) {
                btnB.setIcon(btnxanhla);
            } else {
                btnB.setIcon(btndo);
            }
//            JOptionPane.showMessageDialog(rootPane, "Bạn đã đạt mốc câu hỏi thứ "+String.valueOf(cauhoi)+". Cố gắng lần sau nhé!");
        }

    }//GEN-LAST:event_btnBActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        if (flag) {
            dapannguoichoi = 3;
            flag = false;
            setRolloverAllbutton(false);
            if (kiemtradapan()) {
                btnC.setIcon(btnxanhla);
            } else {
                btnC.setIcon(btndo);
            }
//            JOptionPane.showMessageDialog(rootPane, "Bạn đã đạt mốc câu hỏi thứ "+String.valueOf(cauhoi)+". Cố gắng lần sau nhé!");
        }
    }//GEN-LAST:event_btnCActionPerformed

    private void btnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDActionPerformed
        if (flag) {
            dapannguoichoi = 4;
            flag = false;
            setRolloverAllbutton(false);
            if (kiemtradapan()) {
                btnD.setIcon(btnxanhla);
            } else {
                btnD.setIcon(btndo);
            }
//            JOptionPane.showMessageDialog(rootPane, "Bạn đã đạt mốc câu hỏi thứ "+String.valueOf(cauhoi)+". Cố gắng lần sau nhé!");
        }
    }//GEN-LAST:event_btnDActionPerformed

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        if (flag) {
            dapannguoichoi = 1;
            flag = false;
            setRolloverAllbutton(false);
            if (kiemtradapan()) {
                btnA.setIcon(btnxanhla);
            } else {
                btnA.setIcon(btndo);
            }
//            JOptionPane.showMessageDialog(rootPane, "Bạn đã đạt mốc câu hỏi thứ "+String.valueOf(cauhoi)+". Cố gắng lần sau nhé!");
        }
    }//GEN-LAST:event_btnAActionPerformed

    private void btnTieptucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTieptucActionPerformed
        if (!flag) {
            if (kiemtradapan()) {
                if (cauhoi != 15) {
                    cauhoi++;
                    loadCauhoi(cauhoi);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Chúc Mừng Bạn Đã Hoàn Thành Xuất Sắc 15 Câu Hỏi Của Chúng Tôi!");
                    this.dispose();
                    GameStart gamestart = new GameStart();
                    gamestart.setVisible(true);
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Bạn đã đạt mốc câu hỏi thứ " + String.valueOf(cauhoi) + ". Cố gắng lần sau nhé!");
                this.dispose();
                GameStart gamestart = new GameStart();
                gamestart.setVisible(true);
            }
        }

    }//GEN-LAST:event_btnTieptucActionPerformed

    private void btnDungchoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDungchoiActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new GameStart().setVisible(true);
    }//GEN-LAST:event_btnDungchoiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamePlay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnDungchoi;
    private javax.swing.JButton btnTieptuc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbA;
    private javax.swing.JLabel lbB;
    private javax.swing.JLabel lbBGcauhoi;
    private javax.swing.JLabel lbC;
    private javax.swing.JLabel lbD;
    private javax.swing.JLabel lbSocauhoi;
    private javax.swing.JLabel lbcauhoi;
    // End of variables declaration//GEN-END:variables

}
